version: 2.1
            
jobs:
  build-frontend:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
            
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Back-end build
          command: |
             cd frontend
             npm install
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

            

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend